[2024-01-24T02:55:39.262+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:49:46.059903+00:00 [queued]>
[2024-01-24T02:55:39.342+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:49:46.059903+00:00 [queued]>
[2024-01-24T02:55:39.344+0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T02:55:39.345+0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2024-01-24T02:55:39.345+0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T02:55:39.409+0800] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): train_model> on 2024-01-23 18:49:46.059903+00:00
[2024-01-24T02:55:39.428+0800] {standard_task_runner.py:55} INFO - Started process 78986 to run task
[2024-01-24T02:55:39.473+0800] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2024-01-23T18:49:46.059903+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmph20oivmn']
[2024-01-24T02:55:39.474+0800] {standard_task_runner.py:83} INFO - Job 25: Subtask train_model
[2024-01-24T02:55:39.872+0800] {task_command.py:389} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:49:46.059903+00:00 [running]> on host ml
[2024-01-24T02:55:40.206+0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=youtube_comments_score
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-01-23T18:49:46.059903+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-23T18:49:46.059903+00:00
[2024-01-24T02:55:40.214+0800] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-24T02:55:40.219+0800] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/am/project/scripts/train_model.py']
[2024-01-24T02:55:40.268+0800] {subprocess.py:86} INFO - Output:
[2024-01-24T02:55:40.299+0800] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-24T02:55:40.299+0800] {subprocess.py:93} INFO -   File "/home/am/project/scripts/train_model.py", line 1, in <module>
[2024-01-24T02:55:40.300+0800] {subprocess.py:93} INFO -     from sklearn.linear_model import LinearRegression
[2024-01-24T02:55:40.300+0800] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'sklearn'
[2024-01-24T02:55:40.301+0800] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-24T02:55:40.361+0800] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/am/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-24T02:55:40.367+0800] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=train_model, execution_date=20240123T184946, start_date=20240123T185539, end_date=20240123T185540
[2024-01-24T02:55:40.393+0800] {standard_task_runner.py:100} ERROR - Failed to execute job 25 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 78986)
[2024-01-24T02:55:40.411+0800] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-01-24T02:55:40.540+0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
