[2024-01-24T03:00:45.154+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:49:46.059903+00:00 [queued]>
[2024-01-24T03:00:45.186+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:49:46.059903+00:00 [queued]>
[2024-01-24T03:00:45.186+0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T03:00:45.186+0800] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2024-01-24T03:00:45.186+0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T03:00:45.221+0800] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): train_model> on 2024-01-23 18:49:46.059903+00:00
[2024-01-24T03:00:45.229+0800] {standard_task_runner.py:55} INFO - Started process 83208 to run task
[2024-01-24T03:00:45.236+0800] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2024-01-23T18:49:46.059903+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp9lhmk374']
[2024-01-24T03:00:45.238+0800] {standard_task_runner.py:83} INFO - Job 26: Subtask train_model
[2024-01-24T03:00:45.448+0800] {task_command.py:389} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:49:46.059903+00:00 [running]> on host ml
[2024-01-24T03:00:45.616+0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=youtube_comments_score
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-01-23T18:49:46.059903+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-23T18:49:46.059903+00:00
[2024-01-24T03:00:45.618+0800] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-24T03:00:45.619+0800] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/am/project/scripts/train_model.py']
[2024-01-24T03:00:45.648+0800] {subprocess.py:86} INFO - Output:
[2024-01-24T03:00:45.653+0800] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-24T03:00:45.653+0800] {subprocess.py:93} INFO -   File "/home/am/project/scripts/train_model.py", line 1, in <module>
[2024-01-24T03:00:45.653+0800] {subprocess.py:93} INFO -     from sklearn.linear_model import LinearRegression
[2024-01-24T03:00:45.653+0800] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'sklearn'
[2024-01-24T03:00:45.654+0800] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-24T03:00:45.681+0800] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/am/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-24T03:00:45.685+0800] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=train_model, execution_date=20240123T184946, start_date=20240123T190045, end_date=20240123T190045
[2024-01-24T03:00:45.709+0800] {standard_task_runner.py:100} ERROR - Failed to execute job 26 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 83208)
[2024-01-24T03:00:45.758+0800] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-01-24T03:00:45.796+0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
