[2024-01-24T02:22:24.637+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_test_split_data scheduled__2024-01-23T17:05:00+00:00 [queued]>
[2024-01-24T02:22:24.668+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_test_split_data scheduled__2024-01-23T17:05:00+00:00 [queued]>
[2024-01-24T02:22:24.668+0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T02:22:24.668+0800] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2024-01-24T02:22:24.668+0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T02:22:24.700+0800] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): train_test_split_data> on 2024-01-23 17:05:00+00:00
[2024-01-24T02:22:24.707+0800] {standard_task_runner.py:55} INFO - Started process 50657 to run task
[2024-01-24T02:22:24.789+0800] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_score', 'train_test_split_data', 'scheduled__2024-01-23T17:05:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmpk08e368e']
[2024-01-24T02:22:24.791+0800] {standard_task_runner.py:83} INFO - Job 16: Subtask train_test_split_data
[2024-01-24T02:22:25.119+0800] {task_command.py:389} INFO - Running <TaskInstance: youtube_comments_score.train_test_split_data scheduled__2024-01-23T17:05:00+00:00 [running]> on host ml
[2024-01-24T02:22:25.409+0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=youtube_comments_score
AIRFLOW_CTX_TASK_ID=train_test_split_data
AIRFLOW_CTX_EXECUTION_DATE=2024-01-23T17:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-23T17:05:00+00:00
[2024-01-24T02:22:25.411+0800] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-24T02:22:25.412+0800] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/am/project/scripts/train_test_split_data.py']
[2024-01-24T02:22:25.449+0800] {subprocess.py:86} INFO - Output:
[2024-01-24T02:22:25.450+0800] {subprocess.py:93} INFO - python3: can't open file '/home/am/project/scripts/train_test_split_data.py': [Errno 2] No such file or directory
[2024-01-24T02:22:25.453+0800] {subprocess.py:97} INFO - Command exited with return code 2
[2024-01-24T02:22:25.493+0800] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/am/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-01-24T02:22:25.497+0800] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=youtube_comments_score, task_id=train_test_split_data, execution_date=20240123T170500, start_date=20240123T182224, end_date=20240123T182225
[2024-01-24T02:22:25.526+0800] {standard_task_runner.py:100} ERROR - Failed to execute job 16 for task train_test_split_data (Bash command failed. The command returned a non-zero exit code 2.; 50657)
[2024-01-24T02:22:25.542+0800] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-01-24T02:22:25.609+0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
