[2024-01-24T03:01:14.240+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:55:33.041952+00:00 [queued]>
[2024-01-24T03:01:14.284+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:55:33.041952+00:00 [queued]>
[2024-01-24T03:01:14.284+0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T03:01:14.284+0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2024-01-24T03:01:14.284+0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T03:01:14.353+0800] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): train_model> on 2024-01-23 18:55:33.041952+00:00
[2024-01-24T03:01:14.361+0800] {standard_task_runner.py:55} INFO - Started process 83720 to run task
[2024-01-24T03:01:14.388+0800] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_score', 'train_model', 'manual__2024-01-23T18:55:33.041952+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmp85rr1lix']
[2024-01-24T03:01:14.390+0800] {standard_task_runner.py:83} INFO - Job 30: Subtask train_model
[2024-01-24T03:01:14.632+0800] {task_command.py:389} INFO - Running <TaskInstance: youtube_comments_score.train_model manual__2024-01-23T18:55:33.041952+00:00 [running]> on host ml
[2024-01-24T03:01:14.883+0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=youtube_comments_score
AIRFLOW_CTX_TASK_ID=train_model
AIRFLOW_CTX_EXECUTION_DATE=2024-01-23T18:55:33.041952+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-23T18:55:33.041952+00:00
[2024-01-24T03:01:14.885+0800] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-24T03:01:14.886+0800] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/am/project/scripts/train_model.py']
[2024-01-24T03:01:14.916+0800] {subprocess.py:86} INFO - Output:
[2024-01-24T03:01:14.937+0800] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-24T03:01:14.945+0800] {subprocess.py:93} INFO -   File "/home/am/project/scripts/train_model.py", line 1, in <module>
[2024-01-24T03:01:14.946+0800] {subprocess.py:93} INFO -     from sklearn.linear_model import LinearRegression
[2024-01-24T03:01:14.946+0800] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'sklearn'
[2024-01-24T03:01:14.946+0800] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-24T03:01:14.975+0800] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/am/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-24T03:01:14.979+0800] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=train_model, execution_date=20240123T185533, start_date=20240123T190114, end_date=20240123T190114
[2024-01-24T03:01:15.001+0800] {standard_task_runner.py:100} ERROR - Failed to execute job 30 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 83720)
[2024-01-24T03:01:15.040+0800] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-01-24T03:01:15.101+0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
