[2024-01-24T01:42:52.099+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-23T00:05:00+00:00 [queued]>
[2024-01-24T01:42:52.148+0800] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_score.get_data scheduled__2023-01-23T00:05:00+00:00 [queued]>
[2024-01-24T01:42:52.148+0800] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T01:42:52.148+0800] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2024-01-24T01:42:52.148+0800] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-01-24T01:42:52.176+0800] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): get_data> on 2023-01-23 00:05:00+00:00
[2024-01-24T01:42:52.199+0800] {standard_task_runner.py:55} INFO - Started process 10562 to run task
[2024-01-24T01:42:52.211+0800] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_score', 'get_data', 'scheduled__2023-01-23T00:05:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_score.py', '--cfg-path', '/tmp/tmphe2msw89']
[2024-01-24T01:42:52.212+0800] {standard_task_runner.py:83} INFO - Job 4: Subtask get_data
[2024-01-24T01:42:52.484+0800] {task_command.py:389} INFO - Running <TaskInstance: youtube_comments_score.get_data scheduled__2023-01-23T00:05:00+00:00 [running]> on host ml
[2024-01-24T01:42:52.694+0800] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=youtube_comments_score
AIRFLOW_CTX_TASK_ID=get_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T00:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-23T00:05:00+00:00
[2024-01-24T01:42:52.696+0800] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-24T01:42:52.701+0800] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/am/project/scripts/get_data.py']
[2024-01-24T01:42:52.759+0800] {subprocess.py:86} INFO - Output:
[2024-01-24T01:42:53.055+0800] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-01-24T01:42:53.055+0800] {subprocess.py:93} INFO -   File "/home/am/project/scripts/get_data.py", line 3, in <module>
[2024-01-24T01:42:53.055+0800] {subprocess.py:93} INFO -     from pyyoutube import Api
[2024-01-24T01:42:53.055+0800] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'pyyoutube'
[2024-01-24T01:42:53.055+0800] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-24T01:42:53.162+0800] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/am/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-24T01:42:53.181+0800] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_comments_score, task_id=get_data, execution_date=20230123T000500, start_date=20240123T174252, end_date=20240123T174253
[2024-01-24T01:42:53.230+0800] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 10562)
[2024-01-24T01:42:53.303+0800] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-01-24T01:42:53.367+0800] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
